### ISSUE TITLE
Add PROJECT_PATH environment variable

### ISSUE THREAD

**Issue by S-Coyle** [actions-rs/audit-check#116]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation
For a variety of reasons, many projects don't contain their `Cargo.toml` file in their root directory, or they have multiple sub-projects each with their own `Cargo.toml`s. Would it be possible to make the project path configurable? That way the community would benefit from being able to run from a specified path.
We've added this action to a few of our projects and I'm in the process of expanding that to others as it works well, but I've hit this issue which seems to block me from using it in projects such as [here](https://github.com/maidsafe/safe-nodejs/tree/master/native) ~and only the root directory `Cargo.toml in this repo [here](https://github.com/maidsafe/safe-api)~ EDIT: was mistaken about this particular linked repo being an example.

## Workflow example

```yaml
name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
      
  paths: 
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PROJECT_PATH: ./my_sub_folder
```

## Additional context

As far as I'm aware there's no way around this at the moment. Been looking for workarounds to this issue I'm facing and found the `working-directory` option [here](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-8) but turns out it can only be used with `run` and not with `uses`.
Found a [PR here](https://github.com/w9jds/firebase-action/pull/8/files) which seems to have resolved this in another action, hoping something similar would work with audit-check.
