### ISSUE TITLE
Provide a way to pass options to cargo-audit

### ISSUE THREAD

**Issue by taiki-e** [actions-rs/audit-check#132]
## Motivation

cargo-audit has some useful options, and it would be nice to be able to use them via audit-check. For example:
* `--deny-warnings`: Fail if a warning exists -- warnings may be missed by reviewers until the PR has been merged and the issue submitted.
* `--ignore`: Ignore specified advisory -- if fix requires breaking change, the fix may be postponed as it cannot be fixed immediately (especially if that advisory is warning).

## Workflow example

```yaml
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: --deny-warnings --ignore RUSTSEC-2020-0016
```

or

```yaml
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deny-warnings: true
          ignore: [RUSTSEC-2020-0016]
```
