### ISSUE TITLE
`generate-lockfile` overwrites a checked-in Cargo.lock

### ISSUE THREAD

**Issue by mullr** [actions-rs/audit-check#163]
## Description

I have a repo where I've checked in Cargo.lock, since it's producing a binary which I'm shipping. I've just started getting audit violations in CI for this that I cannot reproduce locally. I've tracked this down to the `generate-lockfile` call at the beginning; this updates the checked-in `Cargo-lock`. In my case, it brings in a new vulnerability due to a transitive dependency update.

## Workflow code

```yml
name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

## Expected behavior

If a Cargo.lock is in source control, it should be used as-is.
