### ISSUE TITLE
Add an option to not create issues on failure

### ISSUE THREAD

**Issue by romoh** [actions-rs/audit-check#180]
## Motivation
When using audit-check on schedule, the action automatically creates an issue. However, given this is a security vulnerability it seems creating an issue is not a desired behavior. At least this should be optional through an input to the action.

## Workflow example
``` 
     - uses: actions-rs/audit-check@v2`
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create-issue: false
```

## Additional context
N/A
