### ISSUE TITLE
Report not generated for failing pull request job

### ISSUE THREAD

**Issue by casey** [actions-rs/audit-check#214]
I'm integrating cargo-audit, and it seems not to generate reports when I run it on pull requests. My workflow code is below, and you can see the jobs from a run here:

https://github.com/agora-org/agora/runs/3911274358

The audit step failed, but it did not generate an HTML report page.

Is this because I have it configured to run on `pull_request`?

Here's an example of a previous configuration, where I was running it on `push` and `pull_request`, and both instances failed, but it seems to have only generated a report for the `push` instance:

https://github.com/agora-org/agora/runs/3911258812

Is this expected behavior? I'm happy to enable logging and post the debug logs, but I wanted to make sure that this wasn't just expected behavior first.

## Workflow Code

```yaml
name: Audit
on:
  pull_request:
    branches:
    - master
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
