### ISSUE TITLE
Cron syntax wrong?

### ISSUE THREAD

**Issue by vn971** [actions-rs/audit-check#219]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

The recommended "Scheduled audit" workflow seems to not work: https://github.com/marketplace/actions/rust-audit-check#scheduled-audit

## Workflow code
https://github.com/vn971/rm_rf/blob/master/.github/workflows/cargo-audit.yml
```yaml
name: cargo audit

on:
  schedule:
    - cron: '0 0 0 * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@issue-104
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
 
## Action output
https://github.com/vn971/rm_rf/actions/runs/2272630581/workflow

## Expected behavior

The workflow yml should be valid, the workflow should be able to start (as opposed to syntax failure).

## Additional context

The observed behavior occurs in a very small and public repo, this one: https://github.com/vn971/rm_rf
