### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by MTRNord** [actions-rs/audit-check#222]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

The action crashes with `Error: Resource not accessible by integration` when setting "Workflow permissions" to read only

## Workflow code

```yaml
name: Security audit
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

```
 
## Action output

[logs_122.zip](https://github.com/actions-rs/audit-check/files/8732128/logs_122.zip)

## Expected behavior

It should fail. But the Readme should mention which permissions are required and why these are required

## Additional context

This is probably just missing documentation :)
