### ISSUE TITLE
Add support for --ignore

### ISSUE THREAD

**Issue by djmitche** [actions-rs/audit-check#223]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

Sometimes addressing an advisory is not important for a repository.  Maybe it's only used in test or deprecated code, or is a difficult fix and analysis of the vulnerability shows the repo isn't actually vulnerable.  In those cases, `cargo audit` provides [`--ignore`](https://github.com/rustsec/rustsec/blob/3da6ae86368b1a56442c7ec4eef88429256dc6ab/cargo-audit/src/commands/audit.rs#L69-L75), but it seems this option is not available in the GitHub action.

## Workflow example

```yaml
jobs:
  audit:
    runs-on: ubuntu-latest
    permissions: write-all
    name: "Audit Dependencies"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1                                                                                                                                                                                                                                                                                        
        with:
          ignore:
            - RUSTSEC-2021-0124
          token: ${{ secrets.GITHUB_TOKEN }}
```
