### ISSUE TITLE
"Error: t is not iterable"

### ISSUE THREAD

**Issue by bobbbay** [actions-rs/audit-check#225]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

Under this configuration on a simple project, `cargo audit` fails with this output.

## Workflow code

```yaml
name: Security audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
 
## Action output

```
Error: t is not iterable
```

## Expected behavior

Don't fail.

## Additional context

`cargo audit` runs fine on my local machine.

Additionally, it seems like the last time this was a bug, it was due to a change in `cargo-audit` itself - maybe this is the same thing? #115
