### ISSUE TITLE
Add options for labels

### ISSUE THREAD

**Issue by simonhyll** [actions-rs/audit-check#231]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

When this action creates an issue it would be great if you could specify which labels it should add to that issue. I would personally use it to apply an "automated" label to it so I can filter it out from project boards.

In addition to manually specifying labels I would like labels for the severity. E.g. `severity-unmaintained` and `severity-critical`. This could be toggled on/off with a `severityLabels` bool option. It would also be nice to be able to edit those severity labels.

## Workflow example

```yaml
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ["automated", "audit"]
          severityLabels: true
```
