### ISSUE TITLE
Report formatting

### ISSUE THREAD

**Issue by NickLarsenNZ** [actions-rs/audit-check#233]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

Codeblocks in the security report show `&quot;` instead of `"`

## Workflow code

```yaml
name: Security audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

```

```toml
chrono = { version = "0.4.24", features = ["serde"] } # triggers a security warning (at the time of writing)
```
 
## Action output

The code blocks look like this:

<img width="1229" alt="image" src="https://github.com/actions-rs/audit-check/assets/10092581/cd11b011-c15d-4c5f-baa7-023b47606386">

## Expected behavior

The code blocks should look like:

```toml
chrono = { version = "0.4", default-features = false, features = ["serde"] }
```
